import { Roboto, Poopins } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["400",  "700"],

});


export const metadata = {
  title: "Ecommerce_WebApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable}`}
      >
        <StoreProvider>
          <div>
            <Header />
          </div>
          {children}
          <div>
            <Footer />
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
